spring.application.name=Store_bySpringBoot
spring.datasource.url=jdbc:mysql://localhost:3306/store_byspringboot
spring.datasource.username=root
spring.datasource.password=88888888
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
